version: "3"

dotenv: [".env"]

tasks:
  confirm:
    cmds:
      - echo -n 'Are you sure? [y/N] ' && read ans && [ ${ans:-N} = y ]

  godev:
    desc: Run app in dev mode in localhost.
    cmds:
      - task: goaudit
      - task: goci
      - APP_ENV=dev go run ./cmd/app serve --http=0.0.0.0:8080

  gorun:
    desc: Run app.
    cmds:
      - task: goaudit
      - go run ./cmd/app serve --http=0.0.0.0:8080

  main:
    desc: Run full build process.
    cmds:
      - task: goaudit
      - task: gobuild

  goaudit:
    desc: Run all audits.
    # deps: [vendor]
    cmds:
      - task: gomod
      - task: goformat
      - task: goimports
      - task: govet

  gomod:
    desc: Check mod.
    cmds:
      - go mod tidy
      - go mod verify

  goformat:
    desc: Go format.
    cmds:
      - go fmt ./...

  goimports:
    desc: goimports.
    cmds:
      - goimports -w .

  govet:
    desc: go vet all.
    cmds:
      - go vet ./...

  gobuild:
    desc: Build program.
    cmds:
      - task: gotest
      - CGO_ENABLED=0 go build -ldflags="{{.LINKER_FLAG}}" -o=./bin/app ./cmd/app
      # - GOOS=linux GOARCH=amd64 go build -ldflags="{{.LINKER_FLAG}}" -o=./bin/linux_amd64/app ./cmd/app
    vars:
      BUILD_TIME:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
      GIT_DESC:
        sh: git describe --always --dirty --tags --long
      LINKER_FLAG: -s -w -X main.buildTime={{.BUILD_TIME}} -X main.version={{.GIT_DESC}}

  gobuild-docker:
    desc: Build program in Dockerfile.
    cmds:
      - CGO_ENABLED=0 go build -ldflags="{{.LINKER_FLAG}}" -o=./bin/app ./cmd/app
    vars:
      LINKER_FLAG: -s -w

  vendor:
    desc: Run vendor with mod tidy and verify.
    cmds:
      - task: gomod
      - go mod vendor

  gotest:
    desc: Run go test.
    cmds:
      - go test -race -vet=off ./...

  goci:
    desc: Run golangci-lint.
    cmds:
      - golangci-lint run
