name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    steps:
      runs:
        - echo $FLY_API_TOKEN
  linting:
    uses: ./.github/workflows/golangci-lint.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: [linting]
  deploy:
    uses: ./.github/workflows/fly.yml
    needs: [build]
