name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    uses: ./.github/workflows/golangci-lint.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: [linting]
  deploy:
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    uses: ./.github/workflows/fly.yml
    needs: [build]
